name: Windows tests

on: [push, pull_request]

permissions:
  contents: read

jobs:

  windows-arm64:
    runs-on: windows-2022
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Generate Project
        run: cmake -B build --toolchain .CMake/toolchain_windows_arm64.cmake .
      - name: Build Project
        run: cmake --build build

  windows-x86:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        toolchain: [.CMake/toolchain_windows_x86.cmake, .CMake/toolchain_windows_amd64.cmake]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Generate Project
        run: cmake -B build --toolchain ${{ matrix.toolchain }} .
      - name: Build Project
        run: cmake --build build
      - name: Test dependencies
        run: pip.exe install pytest pytest-xdist pyyaml
      - name: Run tests
        run: |
          python -m pytest --numprocesses=auto -vv --maxfail=10 --ignore=tests/test_code_conventions.py --ignore=tests/test_kat_all.py --junitxml=build\test-results\pytest\test-results.xml
